version: '3'
services:
  anaconda:
    container_name: deeplearningAZ
    image: continuumio/anaconda3
    volumes:
      - ./:/work
    ports:
      - 8888:8867
    entrypoint: ["/bin/bash", "-c", "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/work/notebooks --ip='*' --port=8867 --no-browser --allow-root"]

